// Mock data based on real Toronto reiki healers
export const fetchReikiHealers = async () => {
  // In a real implementation, this would use Google Places API
  return [
    {
      id: "1",
      title: "Reiki Healing Session",
      providerName: "Reiki Room Toronto",
      providerImage:
        "https://api.dicebear.com/7.x/avataaars/svg?seed=reikiroom",
      serviceType: "Energy Healing",
      rating: 4.9,
      price: 90,
      location: "Downtown Toronto",
      distance: "1.2",
      coordinates: { lat: 43.6547, lng: -79.3907 },
      certificationTier: "gold",
      startTime: "2:00 PM",
      duration: 60,
    },
    {
      id: "2",
      title: "Traditional Reiki Treatment",
      providerName: "Urban Healing Centre",
      providerImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=urban",
      serviceType: "Energy Healing",
      rating: 4.7,
      price: 85,
      location: "Yorkville",
      distance: "2.3",
      coordinates: { lat: 43.6709, lng: -79.3957 },
      certificationTier: "silver",
      startTime: "3:30 PM",
      duration: 75,
    },
    {
      id: "3",
      title: "Reiki & Sound Healing",
      providerName: "Healing Hands Toronto",
      providerImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=hands",
      serviceType: "Energy Healing",
      rating: 4.8,
      price: 120,
      location: "The Annex",
      distance: "3.1",
      coordinates: { lat: 43.6626, lng: -79.4 },
      certificationTier: "gold",
      startTime: "1:00 PM",
      duration: 90,
    },
    {
      id: "4",
      title: "Distance Reiki Session",
      providerName: "Zen Wellness",
      providerImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=zen",
      serviceType: "Energy Healing",
      rating: 4.5,
      price: 75,
      location: "Online",
      distance: "0",
      coordinates: { lat: 43.6532, lng: -79.3832 },
      certificationTier: "blue",
      startTime: "11:00 AM",
      duration: 45,
    },
    {
      id: "5",
      title: "Chakra Balancing & Reiki",
      providerName: "Spirit Temple",
      providerImage: "https://api.dicebear.com/7.x/avataaars/svg?seed=spirit",
      serviceType: "Energy Healing",
      rating: 4.2,
      price: 95,
      location: "Little Italy",
      distance: "4.2",
      coordinates: { lat: 43.6552, lng: -79.4147 },
      certificationTier: "unverified",
      startTime: "4:00 PM",
      duration: 60,
    },
  ];
};
